---
title: "Suplementary Materials: Maternal Judgements of Child Numeracy and Reading Ability Predict Gains in Academic Achievement and Interest"
output: 
  hrbrthemes::ipsum:
    toc: true
---
```{r include=FALSE, message=FALSE,warning=FALSE, echo=FALSE}
source(here::here("code","packages.R"))
source(here::here("code","custom_functions.R"))
library(DT)
library(hrbrthemes)
library(drake)
update_geom_font_defaults(font_rc)
```

# Model Fits

```{r, message=FALSE,warning=FALSE, echo=FALSE}
loadd(mplus_sum)
mplus_sum %>%
  select(Title, ChiSqM_Mean, ChiSqM_DF,
         RMSEA_Mean,TLI_Mean, CFI_Mean) %>%
  set_names(c('Model', 'Chi-sq', 'DF', 'RMSEA', 'TLI','CFI')) %>%
  mutate(Model = c('Numeracy RI-CLPM', 'Numeracy CLPM',
                   'Reading CLPM', 'Reading RI-CLPM')) %>%
  arrange(Model) %>%
  datatable(
    caption = "Table S1. Model Fit Statistics for Within and Between Models."
  )
```
_Notes._ RI-CLPM = Random Intercept Cross-lagged panel model (Within model). 
    CLPM = Cross-lagged panel model (Between model)


# Full Results for Between Person Model: Reading
```{r, message=FALSE, warning=FALSE, cache=FALSE, echo=FALSE}
loadd(mplus_out)
mplus_out$mediation_read.out$parameters$ci.unstandardized %>%
  as_tibble() %>%
  filter(str_detect(paramHeader,"ON")) %>%
  mutate(Outcome = str_remove(paramHeader,"\\..+")) %>%
  dplyr::select(Outcome, Predictor = param, 
         Est = est, `-95 CI` = `low2.5`,`+95 CI` = `up2.5`) %>% 
  mutate(Outcome = case_when(
    str_detect(Outcome, "JUD") ~ str_replace(Outcome, 'Y(.)_R_JUD', 'Maternal Judgement Year \\1'),
    str_detect(Outcome, "INT") ~ str_replace(Outcome, 'Y(.)_R_INT', 'Interest Year \\1'),
    str_detect(Outcome, "READ") ~ str_replace(Outcome, 'Y(.)_READ', 'Achievement Year \\1')
  ),
  Predictor = case_when(
    str_detect(Predictor, "JUD") ~ str_replace(Predictor, 'Y(.)_R_JUDGE', 'Maternal Judgement Year \\1'),
    str_detect(Predictor, "INT") ~ str_replace(Predictor, 'Y(.)_R_INT', 'Interest Year \\1'),
    str_detect(Predictor, "READ") ~ str_replace(Predictor, 'Y(.)_READ', 'Achievement Year \\1'),
    Predictor == 'GENDER' ~ 'Girls',
    Predictor == 'SES' ~ 'z-Socioeconomic Status',
    Predictor == 'GEO' ~ 'Urban',
    Predictor == 'INDIG' ~ 'non-Indigenous',
    Predictor == 'LANG' ~ 'LOTE',
  )
  ) %>%
  datatable(filter= 'top', caption = "Table S2. Full Reading CLPM (Between) Model Output")
```

# Full Results for Between Person Model: Math
```{r, message=FALSE, warning=FALSE, cache=FALSE, echo=FALSE}

mplus_out$mediation_math.out$parameters$ci.stdyx.standardized %>%
  as_tibble() %>%
  filter(str_detect(paramHeader,"ON")) %>%
  mutate(Outcome = str_remove(paramHeader,"\\..+")) %>%
  dplyr::select(Outcome, Predictor = param, 
         Est = est, `-95 CI` = `low2.5`,`+95 CI` = `up2.5`) %>% 
  mutate(Outcome = case_when(
    str_detect(Outcome, "JUD") ~ str_replace(Outcome, 'Y(.)_M_JUD', 'Maternal Judgement Year \\1'),
    str_detect(Outcome, "INT") ~ str_replace(Outcome, 'Y(.)_M_INT', 'Interest Year \\1'),
    str_detect(Outcome, "MATH") ~ str_replace(Outcome, 'Y(.)_MATH', 'Achievement Year \\1')
  ),
  Predictor = case_when(
    str_detect(Predictor, "JUD") ~ str_replace(Predictor, 'Y(.)_M_JUDGE', 'Maternal Judgement Year \\1'),
    str_detect(Predictor, "INT") ~ str_replace(Predictor, 'Y(.)_M_INT', 'Interest Year \\1'),
    str_detect(Predictor, "MATH") ~ str_replace(Predictor, 'Y(.)_MATH', 'Achievement Year \\1'),
    Predictor == 'GENDER' ~ 'Girls',
    Predictor == 'SES' ~ 'z-Socioeconomic Status',
    Predictor == 'GEO' ~ 'Urban',
    Predictor == 'INDIG' ~ 'non-Indigenous',
    Predictor == 'LANG' ~ 'LOTE',
  )
  ) %>%
  datatable(filter = 'top', caption = "Table S2. Full Numeracy CLPM (Between) Model Output")
```


# Mediation Effects for Reading Achievement

```{r, message=FALSE, warning=FALSE, cache=FALSE, echo=FALSE}
reading <- my_extract_indirect()
datatable(reading, caption = "Table S3. Reading Total, Direct, and Indirect Effects")
```

# Mediation Effects for Math

```{r, message=FALSE, warning=FALSE, cache=FALSE, echo=FALSE}
math <- my_extract_indirect(file = here("code", "mplus","mediation_math.out"),
                            type = 'Math')
datatable(math, filter = 'top', caption = "Table S4. Reading Total, Direct, and Indirect Effects")
```

# Assumption Checks
```{r, message=FALSE, warning=FALSE, cache=FALSE, echo=FALSE}
library(googlesheets4)
assump <- read_sheet("1qEJvz45Pm6HSDpRQArRQTCF6ecAGidcibhrje3M8iJI")

datatable(assump, filter = 'top', caption = 'Table S5. Assumption Checks')
```
